### ISSUE TITLE
Toggle BubbleListItem

### ISSUE THREAD

**Issue by craig1123** [smollweide/react-speed-dial#6]
I want to toggle an BubbleList item so when I click on it, it disappears. I also want it to reappear if some condition is met in my code.
If I try to toggle an item on BubbleList item with this code,
````
{
     this.state.toggle ?
       <BubbleListItem
          onTouchTap={this.handleIconClick.bind(this)}
          primaryText='Points'
          rightAvatar={<Avatar backgroundColor={blue500} icon={<PlusOne />} />}
          />
      : null
}
````
`handleIconClick(){
       this.setState({toggle:false})
}`

I receive the error, "Cannot read property 'type' of null" at bubble-list.js:104.

Is there some way of adding this feature?

 Thank you

**Comment by smollweide** [comment]
@craig1123 
It's fixed with in v0.3.0
`npm install react-speed-dial@0.3.0`

Thanks for the report.

**Comment by craig1123** [comment]
@smollweide I appreciate the fast response.
After updating the npm package, my speed dial still does not recognize null children in the BubbleListItem. 

Before clicking child:
![before](https://cloud.githubusercontent.com/assets/17581359/21199023/ee99a8c6-c1fe-11e6-8f41-33ecd3faeede.png)

After clicking child:
![after](https://cloud.githubusercontent.com/assets/17581359/21199044/02dac7f2-c1ff-11e6-837e-f91cca6febe8.png)

The node turns into a white square. Can this be fixed?

**Comment by smollweide** [comment]
Hi @craig1123,
I added a demo page for your described problem.
- Page: [example page bug6](https://smollweide.github.io/react-speed-dial/#/bug6)
- Code: [example-bug6.js](https://github.com/smollweide/react-speed-dial/blob/develop/src/examples/example-bug6/example-bug6.js)

I tested it on Chrome@latest, FF@47 and Safari@10.0.1 (iOS and Mac).

Can you please add more details?

**Comment by craig1123** [comment]
ah,

Before I had 
```{list.items.map((item, index) => {
		return (<BubbleListItem key={index} {...item} />);
       })}
```

but after looking at your example code, I spread them out instead of doing a .map. That seemed to do the trick :). Thank you
